## THEME
theme: hugolify-theme

## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
paginate: 18
enableRobotsTXT: true
markup:
  tableOfContents:
    ordered: true
build:
  writeStats: true

## STATIC
staticDir:
  - static1
  - static2
