## THEME
theme: hugo-theme

## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
paginate: 18
enableRobotsTXT: true
build:
  writeStats: true

## STATIC
staticDir:
  - static1
  - static2
