## LANGUAGE
defaultContentLanguage: fr

## ADVANCED
build:
  writeStats: true
enableRobotsTXT: true
imaging:
  quality: 80
markup:
  tableOfContents:
    ordered: true
pagination:
  pagerSize: 18
removePathAccents: true
timeout: 100000
