[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.138.0"
  GO_VERSION = "1.23.3"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  # HUGO_ENV = "staging"
  HUGO_ENV = "production"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"