export const availableBlocks = [
    'alert',
    'cta',
    'informations',
    'pushes',
    'datas',
    // 'map',
    'quote',
    'latest',
    'editorial',
    'embed',
    'figure',
    'gallery',
    'images',
    'paragraph',
    // 'selectedposts',
    'selectedcasestudies',
    // 'selectedprojects',
    // 'selectedpublications',
    'title'
];